name: Build and Release JAR

on:
  push:
    tags:
      - 'v*' # Triggers on version tags v1.0.0, v2.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Adjust version as needed
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew carbon:build

      - name: Get JAR file
        id: get-jar
        run: |
          JAR_PATH=$(find build/libs -name "*.jar" -type f)
          echo "jar_path=$JAR_PATH" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.get-jar.outputs.jar_path }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}